//
//  MockSchoolsImplementation.swift
//  MacroCHallengeApp
//
//  Created by João Pedro de Amorim on 05/10/20.
//

import Foundation
import UIKit

class MockSchoolsImplementation: SchoolsProtocol {
	// MARK: - SchoolsProtocol methods
	func getSchools() -> [School] {
		return hardCodedSchools()
	}

	/**

	Método que retorna escolas a partir do hardcoding delas. É necessário fazer o hardcoding dos atributos da escola também: (provas, questões...)

	- returns: Um array que contém todas as escolas hardcoded.

	*/

	private func hardCodedSchools() -> [School] {
		guard let imgCti1 = UIImage(named: "CTI2020questionImage01") else {return []}
		guard let imgCti2 = UIImage(named: "CTI2020questionImage02") else {return []}
		guard let imgCti3 = UIImage(named: "CTI2020questionImage03") else {return []}
		guard let imgCti4 = UIImage(named: "CTI2020questionImage04") else {return []}
		guard let imgCti5 = UIImage(named: "CTI2020questionImage05") else {return []}
		guard let imgCti6 = UIImage(named: "CTI2020questionImage06") else {return []}
		guard let imgCti7 = UIImage(named: "CTI2020questionImage07") else {return []}
		guard let imgCti8 = UIImage(named: "CTI2020questionImage08") else {return []}
		guard let imgCti9 = UIImage(named: "CTI2020questionImage09") else {return []}
		guard let imgCti10 = UIImage(named: "CTI2020questionImage10") else {return []}
		guard let imgCti11 = UIImage(named: "CTI2020questionImage11") else {return []}
		guard let imgCti12 = UIImage(named: "CTI2020questionImage12") else {return []}
		guard let imgCti13 = UIImage(named: "CTI2020questionImage13") else {return []}
		guard let imgCti14 = UIImage(named: "CTI2020questionImage14") else {return []}
		guard let imgCti15 = UIImage(named: "CTI2020questionImage15") else {return []}
		guard let imgCti16 = UIImage(named: "CTI2020questionImage16") else {return []}
		guard let imgCti17 = UIImage(named: "CTI2020questionImage17") else {return []}

		let CtiFirstDummyQuestion = Question(number: "1",
											 text: "O efeito de humor da tira ocorre com a interpretação equivo- cada que o segundo personagem faz do termo",
											 initialText: "Leia a tira.",
											 images: [imgCti1],
											 subtitle: "(Mort Walker, “Recruta Zero”. Em: https://cultura.estadao.com.br/quadrinhos)",
											 options: ["a":"sargento.", "b":"exposição.", "c":"ele.", "d":"venceu."],
											 answer: "c",
											 topic: "Português")
		let CtiSecondDummyQuestion = Question(number: "2",
											  text: "As informações textuais permitem concluir que",
											  initialText: "Leia o texto para responder às questões de números 02 a 09.\n\nO mundo dos selos raros\n\nSelos parecem coisas ultrapassadas e fora de moda. Não embelezam mais as cartas, hoje se preferem carimbos, e nem tantas cartas se usam. Foi-se o tempo em que receber um envelope com selo bonito era uma alegria e também uma fonte de informação. Certamente há muitas crianças, hoje em dia, que nem sabem o que é um selo.Apesar dessa notável insignificância, na semana passada, num leilão na Alemanha, vendeu-se um deles pela incrível soma de 1,26 milhão de euros. Se for considerado pelo seu peso, é um dos objetos mais valiosos que existem. Seu nome é Erro de impressão Baden. Foi impresso num tom verde azulado em vez do padrão rosa lilás de sua série. Está estampado num envelope datado de 26 de agosto de 1851. Só existem dois selos do tipo, de 9 centavos, com o mesmo erro. O outro está na coleção do Museu Postal de Berlim.Esse não é o preço mais alto já pago por um selo. Na Europa, o Three Skilling Yellow, impresso na Suécia, em 1855, foi vendido nos anos 1990 por 2,2 milhões de dólares. Há também o imbatível Black on Magenta, que mede 2,5 por 3,8 centímetros e foi produzido na Guiana Francesa em 1856, quando houve uma escassez de selos vindos da Inglaterra, o que ameaçava as reservas postais. Foi impresso em pequena tiragem na gráfica de um jornal e o único magenta de um penny que sobreviveu foi esse. Leiloado pela Sotheby’s de Nova York, em 2014, foi arrematado por US$ 9,5 milhões. O diretor de projetos especiais da casa de leilões, David Redden, classificou-o como “um objeto mágico, a definição própria de raridade e valor em um nível extraordinário”. O selo mostra uma imagem de um navio de três mastros e o lema dos colonos britânicos: “Nós damos e esperamos retorno”.",
											  images: nil,
											  subtitle: "(Vicente Vilardaga, “O mundo dos selos raros”. IstoÉ, 19.06.2019. Adaptado)",
											  options: ["a":"sos selos estão sendo cada vez menos usados, mas ainda podem ser negócios muito rentáveis.", "b":"os leilões de selos têm levado a população a mandar mais cartas do que em outros tempos.", "c":"a inexistência de selos hoje em dia tem feito o comércio desse produto ficar menos rentável.", "d":"os países estão produzindo mais selos, empolgados com os valores que estes têm obtido em leilões."],
											  answer: "a",
											  topic: "Português")
		let CtiThirdDummyQuestion = Question(number: "3",
											 text: "De acordo com o segundo parágrafo do texto, no leilão na Alemanha, o valor pago ao selo “Erro de impressão Baden” foi determinado",
											 initialText: "O texto das questões 2-9 está contido na questão 2",
											 images: nil,
											 subtitle: nil,
											 options: ["a":"pelo seu tamanho reduzido.", "b":"pelo defeito que o torna raro.", "c":"pela data estampada no envelope.", "d":"pelo preço pago originalmente por ele."],
											 answer: "b",
											 topic: "Português")
		let CtiFourthDummyQuestion = Question(number: "4",
											  text: "Na frase “Se for considerado pelo seu peso, é um dos objetos mais valiosos que existem.”, a conjunção destacada expressa sentido de",
											  initialText: "O texto das questões 2-9 está contido na questão 2",
											  images: nil,
											  subtitle: nil,
											  options: ["a":"condição, sugerindo que o valor de um selo pode ser extremamente alto em comparação ao seu peso.", "b":"causa, sugerindo que a avaliação de um selo deve ignorar o peso que ele possa ter de fato.", "c":"conclusão, sugerindo que o selo, como os demais objetos valiosos do mundo, é avaliado pelo peso.", "d":"comparação, sugerindo que o valor comercial de um selo é compatível com o seu peso físico."],
											  answer: "a",
											  topic: "Português")
		let CtiFifthDummyQuestion = Question(number: "5",
											 text: "Assinale a alternativa em que o predicado nominal descreve uma relação positiva das pessoas com os selos.",
											 initialText: "O texto das questões 2-9 está contido na questão 2",
											 images: nil,
											 subtitle: nil,
											 options: ["a":"Selos parecem coisas ultrapassadas e fora de moda.", "b":"... receber um envelope com selo bonito era uma alegria...", "c":"O outro está na coleção do Museu Postal de Berlim.", "d":"... e o único magenta de um penny que sobreviveu foi esse."],
											 answer: "b",
											 topic: "Português")
		let CtiSixthDummyQuestion = Question(number: "6",
											 text: "Nos enunciados “Selos parecem coisas ultrapassadas” (1o parágrafo) e “quando houve uma escassez de selos vindos da Inglaterra” (3o parágrafo), os termos destacados são antônimos, respectivamente, de",
											 initialText: "O texto das questões 2-9 está contido na questão 2",
											 images: nil,
											 subtitle: nil,
											 options: ["a":"promissoras; diminuição.", "b":"conservadoras; exagero.", "c":"desinteressantes; falta.", "d":"inovadoras; abundância."],
											 answer: "d",
											 topic: "Português")
		let CtiSeventhDummyQuestion = Question(number: "7",
											   text: "Na passagem do 3o parágrafo “O diretor de projetos espe- ciais da casa de leilões, David Redden, classificou-o como ‘um objeto mágico, a definição própria de raridade e valor em um nível extraordinário’”, o pronome “o”, em destaque, refere-se ao",
											   initialText: "O texto das questões 2-9 está contido na questão 2",
											   images: nil,
											   subtitle: nil,
											   options: ["a":"Black on Magenta.", "b":"Three Skilling Yellow.", "c":"Erro de impressão Baden.", "d":"ao selo do Museu Postal de Berlim."],
											   answer: "a",
											   topic: "Português")
		let CtiEightDummyQuestion = Question(number: "8",
											 text: "Assinale a alternativa em que o enunciado atende à norma-padrão de concordância.",
											 initialText: "O texto das questões 2-9 está contido na questão 2",
											 images: nil,
											 subtitle: nil,
											 options: ["a":"Foi impresso uma pequena tiragem de selos na gráfica de um jornal, já que estava escasso os selos vindos da Inglaterra.", "b":"Como se escreve poucas cartas hoje em dia, certamente deve existir muitas crianças que nem sabem o que é um selo.", "c":"Pagaram-se 1,26 milhão de euros pelo Erro de impressão Baden, mas houveram outros casos de selos vendidos por valores maior.", "d":"9,5 milhões de dólares foram pagos em 2014 pelo Black on Magenta, o único magenta de um penny que sobreviveu."],
											 answer: "d",
											 topic: "Português")
		let CtiNinthDummyQuestion = Question(number: "9",
											 text: "Assinale a alternativa em que o emprego do acento indicativo da crase está em conformidade com a norma-padrão.",
											 initialText: "O texto das questões 2-9 está contido na questão 2",
											 images: nil,
											 subtitle: nil,
											 options: ["a":"Colocados lado à lado, Three Skilling e Black on Magenta são selos valiosos, cobiçados no mundo inteiro.", "b":"Para David Redden, o selo mais caro do mundo chega à ser “um objeto mágico, a definição própria de raridade”.", "c":"Quem foi à Alemanha para participar do leilão do Erro de impressão Baden, viu-o ser arrebatado por 1,26 milhão de euros.", "d":"Devido à certo controle dos selos que viriam da Inglaterra, as reservas postais da Guiana Francesa ficaram ameaçadas."],
											 answer: "c",
											 topic: "Português")
		let CtiTenthDummyQuestion = Question(number: "10",
											 text: "Observando-se a fisionomia de Chico Bento e de sua mãe, conclui-se, correta e respectivamente, que eles expressam",
											 initialText: "Leia a tira para responder às questões de números 10 e 11.",
											 images: [imgCti2],
											 subtitle: "(turmadamonica.com.br)",
											 options: ["a":"raiva e felicidade.", "b":"perplexidade e alegria.", "c":"contentamento e indiferença.", "d":"tristeza e confusão."],
											 answer: "b",
											 topic: "Português")
		let CtiEleventhDummyQuestion = Question(number: "11",
												text: "O efeito de humor da tira ocorre com a interpretação equivocada que o segundo personagem faz do termo",
												initialText: "Leia a tira para responder às questões de números 10 e 11.",
												images: [imgCti2],
												subtitle: "(turmadamonica.com.br)",
												options: ["a":"cria uma forma de expressão verbal de difícil entendimento ao leitor.", "b":"expressa uma forma de comunicação que não ocorre no mundo real.", "c":"altera a forma de representar a fala, usando uma linguagem formal.", "d":"reproduz o modo como as pessoas do campo falam no cotidiano."],
												answer: "d",
												topic: "Português")
		let CtiTwelfthDummyQuestion = Question(number: "12",
											   text: "Assinale a alternativa em que se faz interpretação correta do texto em um enunciado que atende à norma-padrão de acentuação e de ortografia.",
											   initialText: "Leia o texto para responder às questões de números 12 a 15.\n\nVocês conhecem Ibaté?\n\nÉ uma cidade pequenina, muito pequena mesmo, na região de Araraquara.\nFoi lá que nasci e morei com meus avós, até a idade de nove anos. Depois que vovô morreu, vovó resolveu me mandar para São Paulo, viver com tio Dagoberto e tia Eva.\nVovó nunca tinha viajado sozinha a São Paulo, só com vovô Horácio e de carro. Por isso, a família ficou preocupada quando ela anunciou que embarcaríamos, num ônibus da Viação Cometa.\n– Dizem que São Paulo é uma cidade muito perigosa – argumentou tia Frozina –, acho que mamãe não devia viajar sozinha.\n– Bobagens! – disse vovó, sem permitir nenhuma outra discussão. – É só uma cidade como qualquer outra.",
											   images: nil,
											   subtitle: "(Orlando de Miranda, “A casa do tio Dagoberto” (fragmento). Em: Sete faces do humor, 1992. Adaptado)",
											   options: ["a":"A avó discordou da filha Frozina, por que esta não queria a viajem, parecendo ter ciume da mãe andando com o neto por São Paulo.", "b":"A avó acreditava que Ibaté era um lugar perigoso para o neto morar, porisso optou por deixa-lo sob os cuidados do tio.", "c":"A avó estava para realizar sozinha uma viagem, depois que se tornou viúva e decidiu levar o neto para viver com os tios em São Paulo.", "d":"A avó queria manter os mesmos habitos que tinha antes da viuvês, razão pela qual contrariou a filha e levou o neto para uma cidade maior."],
											   answer: "c",
											   topic: "Português")
		let CtiThirteenthDummyQuestion = Question(number: "13",
												  text: "Quanto à predicação, o verbo que não precisa de complemento está corretamente destacado em:",
												  initialText: "O texto das questões 12-15 está contido na questão 12.",
												  images: nil,
												  subtitle: nil,
												  options: ["a":"Vocês conhecem Ibaté?", "b":"Foi lá que nasci e morei com meus avós...", "c":"... vovó resolveu me mandar para São Paulo...", "d":"... disse vovó, sem permitir nenhuma outra discussão."],
												  answer: "b",
												  topic: "Português")
		let CtiFourteenthDummyQuestion = Question(number: "14",
												  text: "No trecho “quando ela anunciou que embarcaríamos”, o sentido expresso pela forma verbal destacada e o sujeito composto que pratica a ação são, correta e respectivamente:",
												  initialText: "O texto das questões 12-15 está contido na questão 12.",
												  images: nil,
												  subtitle: nil,
												  options: ["a":"ação futura no passado; eu e ela.", "b":"pedido; vovó e vovô.", "c":"dúvida; tio Dagoberto e tia Eva.", "d":"certeza; eu e tia Frozina."],
												  answer: "a",
												  topic: "Português")
		let CtiFifteenthDummyQuestion = Question(number: "15",
												 text: "Nas passagens “É uma cidade pequenina” e “– Bobagens! – disse vovó”, as palavras destacadas expressam, respectivamente, sentido de",
												 initialText: "O texto das questões 12-15 está contido na questão 12.",
												 images: nil,
												 subtitle: nil,
												 options: ["a":"lugar muito acolhedor; algo meio confuso.", "b":"lugar pouco agradável; algo preocupante.", "c":"lugar de pequena extensão; algo perigoso.", "d":"lugar muito pequeno; algo sem importância."],
												 answer: "d",
												 topic: "Português")

		let CtiSixteenthDummyQuestion = Question(number: "16",
												 text: "João ganhou R$ 300,00 de aniversário e utilizou esse dinheiro para comprar uma camiseta, uma calça e uma bermuda. A camiseta custou 1/6 desse valor mais R$ 10,00, e a calça custou desse 1/3 valor mais R$ 20,00. Com o valor restante foi possível comprar a bermuda e ainda sobraram R$ 45,00. O valor da bermuda foi",
												 initialText: nil,
												 images: nil,
												 subtitle: nil,
												 options: ["a":"R$ 60,00.",
														   "b":"R$ 75,00.",
														   "c":"R$ 90,00.",
														   "d":"R$ 105,00."],
												 answer: "b",
												 topic: "Matemática")
		let CtiSeventeenthDummyQuestion = Question(number: "17",
												   text: "Sabe-se que:\n•   O time C sofreu 3 gols a menos do que o time B.\n•   O saldo de gols do time A é igual ao número de gols marcados pelo time C.\n\nNessas condições, a soma do número de gols marcados por esses três times juntos foi",
												   initialText: "A tabela mostra algumas informações sobre o número de gols sofridos e o saldo de gols de 3 times, A, B e C, após algumas partidas de um campeonato.",
												   images: [imgCti3],
												   subtitle: nil,
												   options: ["a":"5",
															 "b":"6",
															 "c":"7",
															 "d":"8"],
												   answer: "c",
												   topic: "Matemática")
		let CtiEighteenthDummyQuestion = Question(number: "18",
												  text: "Andrea colocou 3 músicas em seu pen drive. A primeira música tinha duração de 3 minutos e 48 segundos, e a segunda música tinha duração de 2 minutos e 52 segundos. Sabendo que a duração das 3 músicas juntas era de 9 minutos e 15 segundos, então, a duração da terceira música era de",
												  initialText: nil,
												  images: nil,
												  subtitle: nil,
												  options: ["a":"2 minutos e 35 segundos.",
															"b":"2 minutos e 45 segundos.",
															"c":"2 minutos e 55 segundos.",
															"d":"3 minutos e 05 segundos."],
												  answer: "a",
												  topic: "Matemática")
		let CtiNineteenthDummyQuestion = Question(number: "19",
												  text: "Um recipiente contém 20 litros de detergente. Com esse detergente foi possível encher totalmente 15 frascos, cada um deles com 800 mL, e mais alguns frascos, cada um deles com 600 mL. Sabendo que ainda restaram no recipiente 3,2 litros, o número de frascos enchidos, cada um deles contendo 600 mL, foi",
												  initialText: nil,
												  images: nil,
												  subtitle: nil,
												  options: ["a":"5",
															"b":"6",
															"c":"7",
															"d":"8"],
												  answer: "d",
												  topic: "Matemática")
		let CtiTwentiethDummyQuestion = Question(number: "20",
												 text: "Um reservatório, que tem capacidade máxima para 2 400 litros de água, encontra-se vazio. Para encher esse reservatório será utilizada uma mangueira que despeja 16 litros de água a cada 3 minutos. Depois de 3 horas, com a mangueira aberta, o número de litros de água que ainda faltam para encher totalmente esse reservatório, sem transbordar, é",
												 initialText: nil,
												 images: nil,
												 subtitle: nil,
												 options: ["a":"960.",
														   "b":"1150.",
														   "c":"1280.",
														   "d":"1440."],
												 answer: "d",
												 topic: "Matemática")
		let CtiTwentyfirstDummyQuestion = Question(number: "21",
												   text: "Pedro comprou algumas folhas de papel sulfite para realizar alguns trabalhos. Utilizou 30% delas no primeiro trabalho, e ainda restaram 84 folhas. O número de folhas utilizadas no primeiro trabalho foi",
												   initialText: nil,
												   images: nil,
												   subtitle: nil,
												   options: ["a":"30.",
															 "b":"36.",
															 "c":"42.",
															 "d":"48."],
												   answer: "b",
												   topic: "Matemática")
		let CtiTwentysecondDummyQuestion = Question(number: "22",
													text: "Bruno comprou uma bicicleta, pagando em 2 parcelas mensais de R$ 972,00 cada uma. Sabendo que o preço dessa bicicleta à vista, sem desconto, era R$ 1.800,00, então, a taxa mensal de juro simples cobrada foi de",
													initialText: nil,
													images: nil,
													subtitle: nil,
													options: ["a":"2%.",
															  "b":"3%.",
															  "c":"4%.",
															  "d":"5%."],
													answer: "c",
													topic: "Matemática")
		let CtiTwentythirdDummyQuestion = Question(number: "23",
												   text: "Carol comprou um pacote de balas e irá dividi-las em pacotinhos menores, todos com o mesmo número de balas. Se forem colocadas 8 balas em cada pacotinho, será possível fazer N pacotinhos e não ficará bala alguma de fora. Se forem colocadas 5 balas em cada pacotinho, serão feitos N + 3 pacotinhos, e também não ficará bala alguma de fora. O número total de balas que havia no pacote comprado por Carol era",
												   initialText: nil,
												   images: nil,
												   subtitle: nil,
												   options: ["a":"40.",
															 "b":"45.",
															 "c":"50.",
															 "d":"55."],
												   answer: "a",
												   topic: "Matemática")
		let CtiTwentyfourthDummyQuestion = Question(number: "24",
													text: "Márcia tem em sua carteira apenas notas de R$ 2,00 e notas de R$ 5,00, no total de 9 notas. Sabendo que o valor total dessas notas é R$ 36,00, então, o número de notas de R$ 5,00 é",
													initialText: nil,
													images: nil,
													subtitle: nil,
													options: ["a":"3.",
															  "b":"4.",
															  "c":"5.",
															  "d":"6."],
													answer: "d",
													topic: "Matemática")
		let CtiTwentyfifthDummyQuestion = Question(number: "25",
												   text: "Um professor de matemática pediu para seus alunos resolverem a seguinte equação do 2º grau: xˆ2 – 16x + 63 = 0. Após resolver corretamente a equação, Pedro percebeu que as raízes dela eram iguais às idades de seus dois irmãos mais novos, André e Caio. Sabendo que André é mais velho do que Caio, a idade de Caio é",
												   initialText: nil,
												   images: nil,
												   subtitle: nil,
												   options: ["a":"6 anos.",
															 "b":"7 anos.",
															 "c":"8 anos.",
															 "d":"9 anos."],
												   answer: "b",
												   topic: "Matemática")
		let CtiTwentysixthDummyQuestion = Question(number: "26",
												   text: "Sabe-se que o perímetro do quadrado Q2 é 32 cm, e que a área do quadrado Q1 é 4 cm.\n\nA área do quadrado Q3 é igual a",
												   initialText: "A figura é formada por três quadrados Q1, Q2 e Q3.",
												   images: [imgCti4],
												   subtitle: nil,
												   options: ["a":"9 cmˆ2.",
															 "b":"16 cmˆ2.",
															 "c":"25 cmˆ2.",
															 "d":"36 cmˆ2."],
												   answer: "d",
												   topic: "Matemática")
		let CtiTwentyseventhDummyQuestion = Question(number: "27",
													 text: "A distância entre o banco (B) e a farmácia (F) é igual a",
													 initialText: "Em uma avenida reta e plana, há um banco (B), uma farmácia (F), uma mercearia (M), uma padaria (P) e uma igreja (I), conforme mostra a figura.",
													 images: [imgCti5],
													 subtitle: nil,
													 options: ["a":"400 m.",
															   "b":"500 m.",
															   "c":"600 m.",
															   "d":"700 m."],
													 answer: "a",
													 topic: "Matemática")
		let CtiTwentyeightDummyQuestion = Question(number: "28",
												   text: "O comprimento da cerca DE , que separa o canteiro do resto do terreno, é igual a",
												   initialText: "Um terreno retangular ABCD, com 15 m de comprimento por 8 m de largura, teve parte de sua área, na forma de um triângulo retângulo, reservada para o cultivo de temperos, conforme mostra a figura.",
												   images: [imgCti6],
												   subtitle: nil,
												   options: ["a":"6 m.",
															 "b":"8 m.",
															 "c":"10 m.",
															 "d":"12 m."],
												   answer: "c",
												   topic: "Matemática")
		let CtiTwentyninthDummyQuestion = Question(number: "29",
												   text: "Uma caminhonete irá transportar 16 caixas com melões. Em cada caixa serão colocados 12 melões, cada um deles com massa aproximada de 2 kg. Sabendo que cada caixa vazia tem 400 g de massa, então, a massa total (caixas + melões) que essa caminhonete irá transportar será, aproximadamente, de",
												   initialText: nil,
												   images: nil,
												   subtitle: nil,
												   options: ["a":"376,4 kg.",
															 "b":"388,2 kg.",
															 "c":"390,4 kg.",
															 "d":"394,8 kg."],
												   answer: "c",
												   topic: "Matemática")
		let CtiThirtiethDummyQuestion = Question(number: "30",
												 text: "A forma simplificada da expressão (aˆ2 + 4a + 4)(a - 2)/(aˆ2 -4) para a ≠ 2  e  a ≠ –2, é igual a",
												 initialText: nil,
												 images: nil,
												 subtitle: nil,
												 options: ["a":"a + 2",
														   "b":"8a · (a – 2)",
														   "c":"8a + 2",
														   "d":"8aˆ2 + 16"],
												 answer: "a",
												 topic: "Matemática")
		let CtiThirtyfirstDummyQuestion = Question(number: "31",
												   text: "Após medir a quantidade de água colocada na coluna (1), a torneira foi aberta e foi medido o tempo em segundos (2), no qual toda a água presente na coluna demorou para escoar pela torneira. As propriedades do solo que foram medidas em 1 e 2 foram, respectivamente,",
												   initialText: "Em um estudo sobre solo, foi utilizada uma coluna de vidro, com uma torneira adaptada em sua extremidade, conforme ilustração. Em seguida, 100 mL de areia seca foram colocados dentro da coluna. Então, lentamente, foi acrescentado água, até que o nível da água, após preencher os espaços entre os grãos, atingisse a marca de 100 mL.",
												   images: [imgCti7],
												   subtitle: nil,
												   options: ["a":"drenagem e filtração.",
															 "b":"porosidade e permeabilidade.",
															 "c":"densidade e drenagem.",
															 "d":"filtração e estrutura."],
												   answer: "b",
												   topic: "Ciências Naturais")
		let CtiThirtysecondDummyQuestion = Question(number: "32",
													text: "Uma determinada rocha se formou a partir do resfriamento do magma, que ocorreu no interior da crosta terrestre. Após milhares de anos, essa rocha aflorou à superfície terrestre, sofreu intemperismo, os seus constituintes foram transportados por um rio e foram depositados em um grande lago. Após mais alguns milhares de anos, esse material depositado foi compactado e cimentado, dando origem a uma nova rocha. Ao fazer uma pesquisa nessa rocha, foi verificada a presença de ouro.\n\nConsiderando as informações do texto, o ouro foi",
													initialText: "Leia atentamente o texto a seguir.",
													images: nil,
													subtitle: nil,
													options: ["a":"encontrado em uma rocha sedimentar.",
															  "b":"formado pelo intemperismo.",
															  "c":"cimentado pelo magma.",
															  "d":"formado em uma rocha metamórfica."],
													answer: "a",
													topic: "Ciências Naturais")
		let CtiThirtythirdDummyQuestion = Question(number: "33",
												   text: "Ao passar pelos recipientes 1 e 2, a água é submetida, respectivamente, aos processos de",
												   initialText: "A água usada em pias, chuveiros, tanques e máquinas de lavar pode ser reutilizada na limpeza da casa. Como essa água tem muito sabão, detergente, restos de alimentos e gordura, ela deve passar por um tratamento que elimine esses materiais. Para isso, pode ser utilizado o “jardim filtrante”, que consiste em um tanque com o fundo impermeabilizado, contendo areia e brita na parte inferior e água na parte superior, no qual são cultivadas plantas aquáticas, como o aguapé. O processo é apresentado na ilustração a seguir.",
												   images: [imgCti8],
												   subtitle: "(https://agua-sua-linda.tumblr.com/post/159491798163/a-%C3%A1gua-usada-em-pias-chuveiros-tanques-e. Adaptado)",
												   options: ["a":"floculação e desinfecção.",
															 "b":"decomposição e decantação.",
															 "c":"filtração e peneiração.",
															 "d":"decantação e filtração."],
												   answer: "d",
												   topic: "Ciências Naturais")
		let CtiThirtyfourthDummyQuestion = Question(number: "34",
													text: "Um aterro sanitário é uma obra que tem por objetivo o tratamento final dos resíduos da forma mais ambientalmente correta possível. O funcionamento é baseado nas seguintes etapas:\n1 – A base do aterro é feita, colocando-se uma manta impermeável, para evitar vazamento de líquidos, sobre solo que foi compactado.\n2 – Sobre essa manta, é colocado um sistema de drenos para a coleta do chorume, líquido altamente contaminado que, após tratamento adequado, resulta em água limpa, adequada para regar jardins, por exemplo.\n3 – No interior do aterro, é colocado outro sistema de drenos para a coleta do biogás.\n4 – As camadas de resíduos (lixo) são cobertas por camadas de argila. Há, também, um sistema de drenagem que evita infiltração da água da chuva no interior do aterro.\n\nConsiderando as etapas descritas, verifica-se que o aterro sanitário produz materiais que podem ser utilizados, como é o caso do que ocorre em",
													initialText: nil,
													images: nil,
													subtitle: nil,
													options: ["a":"1 e 2.",
															  "b":"2 e 3.",
															  "c":"3 e 4.",
															  "d":"4 e 1."],
													answer: "b",
													topic: "Ciências Naturais")
		let CtiThirtyfifthDummyQuestion = Question(number: "35",
												   text: "Da forma como está montado esse circuito, verifica-se que",
												   initialText: "Observe o circuito elétrico a seguir, constituído por 3 pilhas de 1,5 v cada uma e 4 lâmpadas de igual resistência (L1 a L4).",
												   images: [imgCti9],
												   subtitle: "(https://mnpefprg.furg.br/images/Dissertacao_2013/Produto-Educacional_Diss-Edilson_Torma.pdf. Adaptado)",
												   options: ["a":"a interrupção do circuito em P não afeta o brilho das lâm- padas.",
															 "b":"se o circuito for interrompido em X, a lâmpada L1 ficará acesa.",
															 "c":"a voltagem a ser distribuída no circuito é de 4,5 v.",
															 "d":"o brilho da lâmpada L1 é maior do que as demais lâm- padas."],
												   answer: "c",
												   topic: "Ciências Naturais")
		let CtiThirtysixthDummyQuestion = Question(number: "36",
												   text: "Com relação às formas de energia e suas transformações, é correto afirmar que a energia",
												   initialText: "A energia solar desempenha um papel muito importante em nosso planeta. Além dos processos naturais, essa energia desempenha, atualmente, um papel importante na obtenção de energia para o uso doméstico. A figura a seguir indica algumas transformações de energia que ocorrem quando a energia solar atinge a superfície terrestre.",
												   images: [imgCti10],
												   subtitle: "(https://taldi.com.br/noticia/entenda-como-funciona-a-energia-solar-fotovoltaica/Adaptado)",
												   options: ["a":"térmica do sol é transformada em calor em 1, e, em eletricidade, em 2.",
															 "b":"radiante do sol é transformada em energia elétrica em 2, e, em química, em 3.",
															 "c":"luminosa do sol é transformada em energia térmica em 1, e, em química, em 2.",
															 "d":"solar é transformada em energia cinética em 1, e, em térmica, em 3."],
												   answer: "b",
												   topic: "Ciências Naturais")
		let CtiThirtyseventhDummyQuestion = Question(number: "37",
													 text: "Para atender ao Princípio dos 3Rs, uma escola desenvolveu um programa e realizou as quatro ações descritas a seguir.\n\n1 – A escola solicitou aos alunos para trazer copos não descartáveis para beber água do filtro da escola em substituição aos copos de plástico que não serão mais oferecidos.\n\n2 – Os professores de ciências solicitaram aos alunos que trouxessem vidros vazios de produtos utilizados em casa como vidros de maionese, azeitona, palmito e outros, para acondicionar produtos químicos e pequenos animais conservados em álcool.\n\n3 – Os professores solicitaram aos alunos e ao pessoal da secretaria que trouxessem papel sulfite ou outro tipo de papel que tenha sido utilizado apenas em um dos lados e deixassem na sala de aula para que os alunos pudessem utilizar o outro lado do papel em seus estudos.\n\n4 – O pessoal da cantina da escola colocou em toda a área de recreação recipientes adequados para o descarte de garrafas Pet, embalagens de sucos e latas de refrigerantes.\n\nCorresponde às atividades de Reduzir, Reutilizar e Reciclar (3 Rs), respectivamente, as ações indicadas pelos números",
													 initialText: nil,
													 images: nil,
													 subtitle: nil,
													 options: ["a":"1, 2 e 3.",
															   "b":"1, 2 e 3.",
															   "c":"2, 4 e 3.",
															   "d":"3, 4 e 1."],
													 answer: "b",
													 topic: "Ciências Naturais")
		let CtiThirtyeightDummyQuestion = Question(number: "38",
												   text: "“Utilizava quando ia para as baladas. A sensação imediata é de euforia e perda de inibições. Mas, depois que passava o efeito, sentia um desânimo muito grande e até ânsia de vômito. No dia seguinte, sentia um pouco de depressão. Mas, no fim de semana seguinte, voltava a utilizar. Sentia-me bem, tinha euforia para dançar a noite toda. Com o uso contínuo, aumentei as doses e, um dia após um exagero, quase morri. Minha temperatura aumentou e eu desmaiei.”\n\nO relato trata do consumo de",
												   initialText: "Leia um depoimento, a respeito do uso de drogas.",
												   images: nil,
												   subtitle: nil,
												   options: ["a":"maconha.",
															 "b":"crack.",
															 "c":"anabolizante.",
															 "d":"ecstasy."],
												   answer: "d",
												   topic: "Ciências Naturais")
		let CtiThirtyninthDummyQuestion = Question(number: "39",
												   text: "No esquema, as ações de defesa do organismo que serão realizados pelas células 1 e 2, são, respectivamente:",
												   initialText: "Ao sofrer um ferimento com um objeto perfurocortante, o indivíduo pode se contaminar com bactérias presentes nesse objeto. Então, no local onde esse objeto penetrou, inicia-se uma sequência de ações que tem por objetivo destruir os microrganismos e as substâncias que produzem, e evitar danos ao indivíduo. O processo está representado na ilustração a seguir.",
												   images: [imgCti11],
												   subtitle: "(https://slideplayer.com.br/slide/333859/Adaptado)",
												   options: ["a":"produção de anticorpos e fagocitose.",
															 "b":"produção de antígenos e de anticorpos.",
															 "c":"produção de antígenos e fagocitose.",
															 "d":"produção de anticorpos e de antígenos."],
												   answer: "a",
												   topic: "Ciências Naturais")
		let CtiFortiethDummyQuestion = Question(number: "40",
												text: "O estudo descrito apresentou um método que pode ser eficaz para",
												initialText: "Em 2016, enquanto ainda estudava no ensino médio na cidade de Coxim, região norte de Mato Grosso do Sul, João Victor de Andrade dos Santos descobriu algo que pode mudar a vida de muita gente. O estudante desenvolveu o método para conservar caldo de cana, porque na época, via o pai ter prejuízo por não conseguir conservar o produto, mas essa descoberta vai muito além. Depois de aprimorada, anos depois, foi descoberto que essa técnica pode ser capaz de inativar um protozoário encontrado nas fezes de um inseto presente em locais em que a cana é armazenada.",
												images: nil,
												subtitle: "(https://www.correiodoestado.com.br/cidades/estudante-de-ms-apresenta-projeto-que-pode-isolar-o-transmissor-da/361216/Adaptado)",
												options: ["a":"o tratamento da malária.",
														  "b":"o desenvolvimento da vacina da dengue.",
														  "c":"a prevenção da doença de Chagas.",
														  "d":"a forma de repelir o mosquito da febre amarela."],
												answer: "c",
												topic: "Ciências Naturais")
		let CtiFortyfirstDummyQuestion = Question(number: "41",
												  text: "A maior parte desse bioma encontra-se nas regiões",
												  initialText: "Nesse bioma é marcante a presença de árvores com galhos tortuosos e de casca grossa. Além do estrato arbóreo, apresenta estrato herbáceo, cujos ramos vegetais secam à medida que se estabelece o período de seca. Esses ramos secos propiciam as queimadas recorrentes nesse tipo de bioma. Nessa região podem ser encontradas 67 espécies de mamíferos, 837 de aves, 120 de répteis e 150 de anfíbios.\n\nNo mapa a seguir, estão representadas as cinco regiões brasileiras.",
												  images: [imgCti12],
												  subtitle: "(https://www.estadosecapitaisdobrasil.com/regioes-do-brasil/Adaptado)",
												  options: ["a":"1, 2 e 3.",
															"b":"1, 4 e 5.",
															"c":"2, 4 e 5.",
															"d":"4, 3 e 5."],
												  answer: "a",
												  topic: "Ciências Naturais")
		let CtiFortysecondDummyQuestion = Question(number: "42",
												   text: "Animais como as aves e os mamíferos apresentam a temperatura do corpo constante e não dependem do ambiente para aquecimento de seu corpo, pois reações químicas em suas células produzem energia suficiente para produção de calor, necessário para suas atividades. Esse processo, responsável pela produção de energia no organismo, é denominado",
												   initialText: nil,
												   images: nil,
												   subtitle: nil,
												   options: ["a":"circulação sanguínea.",
															 "b":"movimento muscular.",
															 "c":"isolamento térmico.",
															 "d":"respiração celular."],
												   answer: "d",
												   topic: "Ciências Naturais")
		let CtiFortythirdDummyQuestion = Question(number: "43",
												  text: "Se o ritmo de desmatamento continuar, isso trará consequências como o",
												  initialText: "O gráfico a seguir representa de forma comparativa o desmatamento na Amazônia, nos anos de 2017/2018 e 2018/2019.",
												  images: [imgCti13],
												  subtitle: "(https://aosfatos.org/noticias/cinco-fatos-para-entender-como-e-monitorado-o-desmatamento-na-amazonia/Adaptado)",
												  options: ["a":"aumento da poluição do ar devido à falta de oxigênio.",
															"b":"alagamento dessa região devido ao aumento das chuvas.",
															"c":"desenvolvimento de solo fértil e protegido para o plantio.",
															"d":"desaparecimento de espécies vegetais e animais típicos."],
												  answer: "d",
												  topic: "Ciências Naturais")
		let CtiFortyfourthDummyQuestion = Question(number: "44",
												   text: "Os processos biológicos e químicos que levam à produção do combustível, como descrito no texto, são, respectivamente:",
												   initialText: "O investimento em energias renováveis é essencial para a redução da poluição ambiental. Uma dessas novas alternativas é o etanol celulósico, combustível obtido por meio do aproveitamento do bagaço de cana-de-açúcar, que antes era desperdiçado. Primeiro, realiza-se a quebra dos polissacarídeos presentes no bagaço em açúcares menores e, em seguida, os açúcares são submetidos aos processos biológicos e químicos que levam à produção do álcool.",
												   images: nil,
												   subtitle: "(https://www.ecycle.com.br/component/content/article/35/1600-etanol-celulosico-e-alternativa-mais-sustentavel-na-producao-de-combustivel-por-meio-de-biomassa.htmlAdaptado)",
												   options: ["a":"solidificação e evaporação.",
															 "b":"coagulação e decantação.",
															 "c":"fermentação e destilação.",
															 "d":"digestão e dissolução."],
												   answer: "c",
												   topic: "Ciências Naturais")
		let CtiFortyfifthDummyQuestion = Question(number: "45",
												  text: "Esse processo ocorre devido à ação de organismos que fazem parte de uma cadeia alimentar, atuando como",
												  initialText: "Os métodos de sustentabilidade estão sendo utilizados cada vez mais. Um deles consiste na compostagem, procedimento que resulta na produção de adubo orgânico. Para a compostagem, é possível utilizar o lixo da cozinha e do jardim, misturando-os em um recipiente. É necessário ter duas vezes mais resíduos marrons (serragem, folhas secas, papelão e folhas de jornal) do que verdes (frutas, vegetais, grama, borra de café). Após algumas poucas semanas, os resíduos transformam-se em um fertilizante natural para nutrir o solo.",
												  images: nil,
												  subtitle: nil,
												  options: ["a":"decompositor.",
															"b":"herbívoro.",
															"c":"predador.",
															"d":"produtor."],
												  answer: "a",
												  topic: "Ciências Naturais")
		let CtiFortysixthDummyQuestion = Question(number: "46",
												  text: "As áreas destacadas no mapa",
												  initialText: "Analise o mapa para responder à questão.",
												  images: [imgCti14],
												  subtitle: nil,
												  options: ["a":"têm como características comuns a presença de grande número de árvores e arbustos com folhas largas e sempre verdes que refletem o ambiente com predomínio de forte umidade e de altas temperaturas.",
															"b":"apresentam alternância entre estações secas e chuvosas; a vegetação é constituída, principalmente, por arbustos e árvores de pequeno porte com raízes profundas, folhas grossas e troncos retorcidos.",
															"c":"caracterizam-se pelo clima tropical de altitude com verões quentes e úmidos e invernos secos; as espécies vegetais predominantes são do tipo gramíneas com arbustos que perdem as folhas na estação seca.",
															"d":"apresentam grande biodiversidade, devido, principalmente, à presença de solos com grande umidade que, além de garantirem árvores de grande porte, ainda mantêm inúmeras espécies de mamíferos, insetos e aves."],
												  answer: "b",
												  topic: "Ciências Naturais")
		let CtiFortyseventhDummyQuestion = Question(number: "47",
													text: "Assinale a alternativa que identifica corretamente um dos focos de tensão.",
													initialText: "No continente asiático, é possível identificar focos de tensão geopolítica que colocam em risco a paz daqueles que vivem nos locais que estão envolvidos em conflitos. Observe no mapa da Ásia alguns desses focos de tensão.",
													images: [imgCti15],
													subtitle: nil,
													options: ["a":"I – Turquia e Iraque estão em conflito há quase uma década com o objetivo de estabelecer o domínio econômico sobre parte do Oriente Médio.",
															  "b":"II – Irã é o maior produtor de petróleo da região e tem pretensões de produzir armas nucleares e tornar-se a maior potência militar do Oriente Médio.",
															  "c":"III – Cachemira é um território em permanente disputa entre a Índia, de religião predominantemente hindu, e o Paquistão, de religião muçulmana.",
															  "d":"IV – Coreia do Norte e Coreia do Sul mantêm conflitos há décadas devido à disputa de territórios ricos em urânio, matéria-prima para a produção de armamentos nucleares."],
													answer: "c",
													topic: "Ciências Naturais")
		let CtiFortyeightDummyQuestion = Question(number: "48",
												  text: "A leitura do gráfico e os conhecimentos sobre aspectos socioeconômicos do Brasil permitem concluir que a evolução do número de trabalhadores na agropecuária deveu-se, entre outros fatores,",
												  initialText: "Analise o gráfico.",
												  images: [imgCti16],
												  subtitle: nil,
												  options: ["a":"à substituição de áreas de lavouras pela pecuária que utiliza menos mão de obra.",
															"b":"ao aumento das áreas destinadas à agricultura familiar, poupadora de mão de obra.",
															"c":"aotérminodaexpansãodasfronteirasagrícolasnasregiões Norte e Centro-Oeste.",
															"d":"à modernização das atividades agropecuárias e à consequente ampliação da mecanização."],
												  answer: "d",
												  topic: "Ciências Naturais")
		let CtiFortyninthDummyQuestion = Question(number: "49",
												  text: "A ilustração mostra que",
												  initialText: "Johann Moritz Rugendas esteve no Brasil entre 1821 e 1825, produzindo várias ilustrações, publicadas posteriormente na Europa. Observe uma delas.",
												  images: [imgCti17],
												  subtitle: nil,
												  options: ["a":"o culto religioso contribuiu para a união dos negros nos quilombos.",
															"b":"a vida dos escravos incluiu momentos de lazer, além do trabalho.",
															"c":"a diversidade cultural impediu a integração entre brancos e negros.",
															"d":"o politeísmo dos povos africanos foi preservado nesse ritual religioso."],
												  answer: "b",
												  topic: "Ciências Naturais")
		let CtiFiftiethDummyQuestion = Question(number: "50",
												text: "O texto refere-se",
												initialText: "O planeta era encarado como uma espécie de enorme tabuleiro de xadrez. A partida era disputada por dois jogadores, empenhados em manter as posições que já haviam conquistado – suas áreas de influência – e, tanto quanto possível, tomar novas áreas do adversário. Nenhum país ou região do globo era considerado fora dos limites do jogo: cada casa do tabuleiro estaria, forçosamente, sob domínio de um ou de outro competidor. Tratava-se, porém, de uma partida com características muito especiais. O confronto aberto entre as superpotências provavelmente faria voar pelos ares todas as peças e o próprio tabuleiro.",
												images: nil,
												subtitle: "(José Augusto Dias Jr. e Rafael Roubicek. A era do medo. Adaptado)",
												options: ["a":"às disputas por colônias na África e na Ásia, nas quais as potências europeias conseguiram mercados consumidores e fornecedores.",
														  "b":"ao período conhecido como Paz Armada, que provocou as tensões responsáveis pela eclosão da Primeira Guerra Mundial.",
														  "c":"à bipolarização do mundo após a Segunda Guerra Mundial, em que os países líderes dos blocos capitalista e socialista queriam a hegemonia.",
														  "d":"aos combates diretos entre forças militares norte-americanas e soviéticas na Guerra Fria, que usaram armas químicas e nucleares."],
												answer: "c",
												topic: "Ciências Naturais")


		// Vestibulinho COTUCA 2018
		let Cotuca2018FirstDummyQuestion = Question(number: "1",
													text: "Para uma festa de casamento, foram comprados 560 doces. Essa quantia era suficiente para dividi-los igualmente entre todos os convidados. No dia do casamento, 10 pessoas não puderam comparecer, fazendo com que cada convidado recebesse 1 doce a mais. Se N é o número que representa o total de pessoas que foram convidadas para a festa, então:",
													initialText: nil,
													images: nil,
													subtitle: nil,
													options: ["a":"40 ≤ 𝑁 < 52",
															  "b":"52 ≤ 𝑁 < 64",
															  "c":"64 ≤ 𝑁 < 76",
															  "d":"76 ≤ 𝑁 < 88",
															  "e":"88 ≤ 𝑁 < 100"],
													answer: "d",
													topic: "Matemática")
		let Cotuca2018SecondDummyQuestion = Question(number: "2",
													 text: "Se √𝑥 = 1+ √3, qual é o valor de 𝑥 2 ?",
													 initialText: nil,
													 images: nil,
													 subtitle: nil,
													 options: ["a":"28 + 16√3",
															   "b":"24 + 8√3",
															   "c":"16 + 12√3",
															   "d":"18 + 20√3",
															   "e":"22 + 14√3"],
													 answer: "a",
													 topic: "Matemática")
		let Cotuca2018ThirdDummyQuestion = Question(number: "3",
													text: "Em uma festa de aniversário, o número de adultos era igual a 60% do número de crianças. Após a chegada de mais 12 crianças e 4 adultos, o número de crianças passou a ser o dobro do número de adultos. Depois disso, o total de pessoas presentes na festa (crianças e adultos) é um número cuja soma dos algarismos é igual a:",
													initialText: nil,
													images: nil,
													subtitle: nil,
													options: ["a":"8",
															  "b":"9",
															  "c":"10",
															  "d":"12",
															  "e":"15"],
													answer: "d",
													topic: "Matemática")

		// Vestibulinho COTUCA 2019
		let Cotuca2019FirstDummyQuestion = Question(number: "1",
													text: "Sobre a tirinha de Laerte a seguir e a letra da música “Triste, louca ou má”, é possível afirmar que:",
													initialText: "Leia a tira.",
													images: [UIImage(named: "COTUCA2019questionImage04")!],
													subtitle: "http://oplanetabomba.blogspot.com/2015/10/o-fundamentalismo-e-tentativa-de-moldar.html. Acesso em: 29/07/2018.",
													options: ["a":"ambos os textos possuem uma relação temática ao problematizarem a ideia de normatização de certos comportamentos sociais.",
															  "b":"ambos os textos possuem uma relação temática ao afirmarem a necessidade de superação do conceito tradicional de família.",
															  "c":"os textos se relacionam de modo contrastivo ao problematizarem a noção de família na sociedade moderna.",
															  "d":"os textos se relacionam de modo contrastivo, pois a tirinha de Laerte está centrada na afirmação do estereótipo da família contemporânea, enquanto a música “Triste, louca ou má” concentra-se na superação do papel atribuído à mulher na sociedade moderna.",
															  "e":"os textos se relacionam de modo contrastivo, pois a tirinha de Laerte está centrada na superação do estereótipo da família contemporânea, enquanto a música “Triste, louca ou má” concentra-se na afirmação do papel atribuído à mulher na sociedade moderna."],
													answer: "a",
													topic: "Português")
		let Cotuca2019SecondDummyQuestion = Question(number: "2",
													 text: "Desse modo, um cliente que almoçar dez vezes e ganhar o almoço por conta do restaurante ganhará um desconto cujo valor, aproximadamente, equivale a:",
													 initialText: "Um restaurante faz uma promoção, com a seguinte regra, a seus clientes fidelizados:",
													 images: [UIImage(named: "COTUCA2019questionImage14")!],
													 subtitle: nil,
													 options: ["a":"8,9%.",
															   "b":"9,1%.",
															   "c":"10%.",
															   "d":"10,9%",
															   "e":"11,1%."],
													 answer: "b",
													 topic: "Matemática")
		let Cotuca2019ThirdDummyQuestion = Question(number: "3",
													text: "Uma fruta in natura possui 80% de sua massa composta de água e, se for desidratada, a água se reduz a 10% da massa após esse processo. Qual é a massa (em gramas) dessa fruta in natura que corresponderia a uma porção de 100 g dessa mesma fruta em sua forma desidratada?",
													initialText: nil,
													images: nil,
													subtitle: nil,
													options: ["a":"900g",
															  "b":"890g",
															  "c":"800g",
															  "d":"450g",
															  "e":"170g"],
													answer: "d",
													topic: "Matemática")

		// Vestibulinho ETEC 2019
		let Etec2019FirstDummyQuestion = Question(number: "1",
												  text: "Considerando os animais citados no texto, podemos afirmar que",
												  initialText: "Os primeiros animais surgiram nos mares e eram invertebrados de corpo mole. À medida que o tapete verde desenvolvia-se sobre a Terra, outro grupo de criaturas vivas – os artrópodes – chegava do mar para desfrutar dessa nova e enorme massa de alimentos. Os primeiros artrópodes que emergiram foram talvez os miriápodes primitivos, que atingiam aproximadamente dois metros de comprimento e apresentavam até duzentas patas. Depois vieram as lacraias, as aranhas e os escorpiões. Tempos depois, surgiram as libélulas gigantes, um dos primeiros insetos a voar, com até setenta centímetros de envergadura. O voo foi, talvez, desenvolvido para que esses insetos escapassem dos animais predadores, que os espreitavam no chão. As baratas, os gafanhotos e os grilos também faziam parte dos conjuntos de primeiros insetos que apareceram.",
												  images: nil,
												  subtitle: nil,
												  options: ["a":"todos possuem asas, corpo mole e segmentado",
															"b":"as lacraias apresentam endoesqueleto calcário e patas articuladas.",
															"c":"os gafanhotos, os grilos e as aranhas possuem um par de antenas e quatro pares de patas.",
															"d":"as libélulas possuem exoesqueleto, três pares de patas e corpo segmentado em cabeça, tórax e abdome.",
															"e":"as baratas, as aranhas e os escorpiões apresentam glândulas de veneno, exoesqueleto e corpo não segmentado. "],
												  answer: "d",
												  topic: "Ciências Naturais")

		let Etec2019SecondDummyQuestion = Question(number: "2",
												   text: "O texto faz referência a um período muito conhecido da história da Humanidade, no qual surgiram os primeiros registros escritos. Assinale a alternativa que, corretamente, descreve o contexto em que surgiu a escrita na Mesopotâmia.",
												   initialText: "Em 1929, o arqueólogo alemão Julius Jordan desenterrou uma vasta biblioteca de tábuas de argila com um tipo de escrita conhecida como “cuneiforme”, com cinco mil anos de idade, mais antigas que exemplares semelhantes encontrados na China, no Egito e na América. As tábuas estavam em Uruk, uma cidade mesopotâmica – e uma das primeiras do mundo – às margens do rio Eufrates, onde hoje fica o Iraque. As tábuas não haviam sido usadas para escrever poesia ou enviar mensagens a lugares remotos. Foram empregadas para fazer contas – e também para elaborar os primeiros contratos.",
												   images: nil,
												   subtitle: "<https://tinyurl.com/ycuj8mq6> Acesso em: 26.10.2018. Adaptado.",
												   options: ["a":"Os mesopotâmicos criaram a escrita como forma de se comunicar com os deuses, entalhando placas de argila que eram cuidadosamente depositadas no interior dos templos religiosos. ",
															 "b":"O surgimento da escrita foi vinculado à criação de um sistema de educação segundo o qual todas as crianças deveriam dominar o conhecimento das letras e dos cálculos.",
															 "c":"As cidades da Mesopotâmia eram separadas por longas distâncias, percorridas a pé por mensageiros que levavam cartas e ofícios trocados entre os governantes.",
															 "d":"A evolução da literatura oral gerou a necessidade de registrar os textos poéticos declamados pelos grandes oradores da Antiguidade clássica.",
															 "e":"O desenvolvimento do comércio levou à criação da escrita, utilizada, inicialmente, para realizar registros contábeis e firmar contratos."],
												   answer: "e",
												   topic: "História")
		let Etec2019ThirdDummyQuestion = Question(number: "3",
												  text: "Um país que se candidate a membro desse bloco econômico deve necessariamente",
												  initialText: "O Tratado da União Europeia estabelece que qualquer país europeu pode se candidatar à adesão ao bloco. Porém, um país só pode entrar na União Europeia se cumprir alguns critérios de adesão.",
												  images: nil,
												  subtitle: nil,
												  options: ["a":"ser republicano e possuir economia de mercado, porém submetida a controles constantes por parte do Fundo Monetário Internacional (FMI).",
															"b":"permanecer fiel à legislação do bloco e delegar suas questões de segurança nacional à Organização do Tratado do Atlântico Norte (OTAN).",
															"c":"possuir regime monarquista de governo, aceitar a política econômica do bloco e se comprometer a utilizar o Euro.",
															"d":"estar situado na Europa Ocidental e substituir sua Câmara de Deputados e seu Senado pelo Parlamento Europeu.",
															"e":"ter instituições estáveis que garantam a democracia, o Estado de direito e o respeito aos direitos humanos."],
												  answer: "e",
												  topic: "História")

		// Vestibulinho ETEC 2020
		let Etec2020FirstDummyQuestion = Question(number: "1",
												  text: "Analise as alternativas e assinale a correta",
												  initialText: "Um número natural, diferente de zero e diferente de um, pode ser classificado como primo ou composto.Os quadrinhos fornecem algumas pistas sobre o que permite caracterizar um número para que ele seja dito primo.",
												  images: [UIImage(named: "ETEC2020questionImage01")!],
												  subtitle: "<https://tinyurl.com/y2xxx63q> Acesso em: 07.10.2019. Original colorido.",
												  options: ["a":"O número 6 056 529 316 217 não é primo, e por isso está distante do restante.",
															"b":"Como os números 37 e 73 são primos, então 16 e 61 também são.",
															"c":"O número 237 é um número primo, assim como o 37 e o 137.",
															"d":"Todo número primo é ímpar e só pode terminar em 1, 3, 7 ou 9.",
															"e":"Há apenas quatro números primos que são menores do que 10."],
												  answer: "e",
												  topic: "Matemática")

		let Etec2020SecondDummyQuestion = Question(number: "2",
												   text: "Assim, na pele, entre os fatores que contribuem para a manutenção da temperatura corporal em dias frios, em ambientes abertos, destacam-se",
												   initialText: "A pele, maior órgão do corpo humano, é importante na manutenção da saúde porque reveste toda a superfície corporal, atuando, entre outras coisas, na proteção contra germes e raios solares, e é também responsável pela sensibilidade tátil e pela manutenção da temperatura corporal. O ser humano apresenta a temperatura corporal normal de 36,5 ºC. A elevação ou redução dessa temperatura pode ter efeitos danosos ao organismo.",
												   images: nil,
												   subtitle: nil,
												   options: ["a":"a dilatação dos vasos sanguíneos periféricos e maior eliminação de oleosidade pelas glândulas sebáceas.",
															 "b":"a dilatação dos vasos sanguíneos periféricos e maior eliminação de suor pelas glândulas sudoríparas.",
															 "c":"a dilatação dos vasos sanguíneos periféricos e eliminação contínua de suor pelas glândulas sebáceas.",
															 "d":"a contração dos vasos sanguíneos periféricos e menor eliminação de suor pelas glândulas sudoríparas.",
															 "e":"a contração dos vasos sanguíneos periféricos e maior eliminação de suor pelas glândulas sebáceas."],
												   answer: "d",
												   topic: "Matemática")
		let Etec2020ThirdDummyQuestion = Question(number: "3",
												  text: "De acordo com o texto, é correto afirmar que",
												  initialText: "Sabemos que a humanidade é capaz de produzir o necessário para banir do planeta o problema da subalimentação. Apesar disso, a fome no mundo concentra-se em países da África subsaariana (e, em menor proporção, na Índia e no Paquistão) e persiste por causa do protecionismo econômico dos países ricos. A esmagadora maioria dos que não conseguem preencher suas necessidades básicas vive em regiões rurais, e a escassa renda que obtêm deriva da agricultura. Aumentar a produção agropecuária é fundamental, como bem sublinhou o secretário-geral da ONU, mas o mais importante é criar condições para que os que vivem em situação de pobreza absoluta conquistem o direito de produzir a própria alimentação.",
												  images: nil,
												  subtitle: "<https://tinyurl.com/y3837qsq> Acesso em: 01.10.2019. Adaptado",
												  options: ["a":"a subalimentação inexiste em países considerados subdesenvolvidos.",
															"b":"a subalimentação atinge principalmente os moradores das áreas urbanas.",
															"c":"o aumento da produção industrial acabará com o problema da subalimentação.",
															"d":"é possível acabar com o problema da subalimentação no mundo em que vivemos.",
															"e":"é a proteção militar dada pelos países pobres aos países ricos que causa a subalimentação."],
												  answer: "d",
												  topic: "História")

		let dummyTest: [Test] = [Test(name: "Prova 2019",
									  year: "2019",
									  questions: [CtiFirstDummyQuestion,
												  CtiSecondDummyQuestion,
												  CtiThirdDummyQuestion,
												  CtiFourthDummyQuestion,
												  CtiFifthDummyQuestion,
												  CtiSixthDummyQuestion,
												  CtiSeventhDummyQuestion,
												  CtiEightDummyQuestion,
												  CtiNinthDummyQuestion,
												  CtiTenthDummyQuestion,
												  CtiEleventhDummyQuestion,
												  CtiTwelfthDummyQuestion,
												  CtiThirteenthDummyQuestion,
												  CtiFourteenthDummyQuestion,
												  CtiFifteenthDummyQuestion,
												  CtiSixteenthDummyQuestion,
												  CtiSeventeenthDummyQuestion,
												  CtiEighteenthDummyQuestion,
												  CtiNineteenthDummyQuestion,
												  CtiTwentiethDummyQuestion,
												  CtiTwentyfirstDummyQuestion,
												  CtiTwentysecondDummyQuestion,
												  CtiTwentythirdDummyQuestion,
												  CtiTwentyfourthDummyQuestion,
												  CtiTwentyfifthDummyQuestion,
												  CtiTwentysixthDummyQuestion,
												  CtiTwentyseventhDummyQuestion,
												  CtiTwentyeightDummyQuestion,
												  CtiTwentyninthDummyQuestion,
												  CtiThirtiethDummyQuestion,
												  CtiThirtyfirstDummyQuestion,
												  CtiThirtysecondDummyQuestion,
												  CtiThirtythirdDummyQuestion,
												  CtiThirtyfourthDummyQuestion,
												  CtiThirtyfifthDummyQuestion,
												  CtiThirtysixthDummyQuestion,
												  CtiThirtyseventhDummyQuestion,
												  CtiThirtyeightDummyQuestion,
												  CtiThirtyninthDummyQuestion,
												  CtiFortiethDummyQuestion,
												  CtiFortyfirstDummyQuestion,
												  CtiFortysecondDummyQuestion,
												  CtiFortythirdDummyQuestion,
												  CtiFortyfourthDummyQuestion,
												  CtiFortyfifthDummyQuestion,
												  CtiFortysixthDummyQuestion,
												  CtiFortyseventhDummyQuestion,
												  CtiFortyeightDummyQuestion,
												  CtiFortyninthDummyQuestion,
												  CtiFiftiethDummyQuestion]),
								 Test(name: "Prova 2018",
									  year: "2018",
									  questions: [Cotuca2019FirstDummyQuestion,
												  Cotuca2019SecondDummyQuestion,
												  Cotuca2019ThirdDummyQuestion]),
								 Test(name: "Prova 2017",
									  year: "2017",
									  questions: [Cotuca2018FirstDummyQuestion,
												  Cotuca2018SecondDummyQuestion,
												  Cotuca2018ThirdDummyQuestion]),
								 Test(name: "Prova 2019",
									  year: "2019",
									  questions: [Etec2020FirstDummyQuestion,
												  Etec2020SecondDummyQuestion,
												  Etec2020ThirdDummyQuestion]),
								 Test(name: "Prova 2019",
									  year: "2019",
									  questions: [Etec2019FirstDummyQuestion,
												  Etec2019SecondDummyQuestion,
												  Etec2019ThirdDummyQuestion])]


		let topics = ["Matemática":["Operações com números inteiros e fracionários",
									 "Sistema de medidas usuais",
									 "Números racionais relativos",
									 "Regra de três simples",
									 "Porcentagem",
									 "Juros simples",
									 "Equação do primeiro grau e sistema simples do primeiro grau",
									 "Equação simples do segundo grau",
									 "Geometria plana (perímetro e área de polígonos regulares, medidas de ângulos)",
									 "Teorema de Pitágoras",
									 "Resolução de situação-problema",
									 "Propriedades da multiplicação comutativa, associativa e distributiva",
									 "Fatoração",
									 "Simplificação de expressões algébricas.",
									 "Produtos notáveis"],
					  "Português":["Interpretação de texto",
									"Sinônimos e antônimos",
									"sinônimos e antônimos",
									"acentuação gráfica",
									"flexão de gênero, número e grau do substantivo e do adjetivo",
									"crase",
									"emprego de pronomes e verbos",
									"emprego de preposições e conjunções",
									"concordância nominal e verbal",
									"predicação verbal",
									"modos verbais e conjugação",
									"acentuação",
									"sintaxe: tipos de sujeito e tipos de predicado",
									"figuras de linguagem",
									"linguagens e variações linguísticas"],
					  "Ciências Naturais":["Drogas: categorias, efeitos, problemas sociais e de  saúde decorrentes do uso",
											"métodos contraceptivos humanos",
											"sistema imunológico, antígenos e anticorpos, vacinas e soros",
											"antibióticos",
											"modo de transmissão, profilaxia e sintomas das doenças: AIDS, dengue, doença de Chagas e febre amarela",
											"características básicas dos seres vivos: organização celular, subsistência – obtenção de matéria e energia e reprodução",
											"os reinos dos seres vivos",
											"tipos de ambientes e especificidade como caracterização, localização geográfica, biodiversidade, proteção e conservação dos ecossistemas brasileiros",
											"relações alimentares – produtores, consumidores e decompositores e transferência de energia entre seres vivos",
											"consequências ambientais do desmatamento indiscriminado",
											"importância da reciclagem do papel",
											"visão geral de propriedades dos materiais, como cor, dureza, brilho, temperaturas de fusão e de ebulição, condutividade elétrica, permeabilidade e suas relações com o uso no cotidiano e no sistema produtivo",
											"minerais, rochas e solos – características gerais e importância para a obtenção de materiais como metais, cerâmicas, vidro, cimento e cal",
											"tecnologia da cana – açúcar e álcool",
											"tecnologia do petróleo",
											"processos físicos de separação de misturas",
											"análise dos conceitos de substância simples, substância pura, mistura, fase e componente",
											"poluição do ar, água e do solo: fontes e efeitos sobre a saúde",
											"efeito estufa e aquecimento global",
											"tratamento de água e esgoto",
											"saneamento básico",
											"a coleta e os destinos do lixo: coleta seletiva, lixões, aterros, incineração, reciclagem e reaproveitamento de materiais",
											"o consumo consciente e a importância dos 3Rs (reduzir, reutilizar e reciclar)",
											"materiais como fonte de energia: petróleo, carvão, gás natural e biomassa como recursos energéticos",
											"interpretação das leis ponderais",
											"análise cronológica da evolução atômica",
											"noções de reações químicas",
											"situações simples do cotidiano que envolvam: movimentos dos corpos (cinemática escalar)",
											"densidade",
											"transformações de energia",
											"aplicações das Leis de Newton",
											"eletricidade básica (átomo, corpos condutores e isolantes, eletrizados e neutros, montagem de circuitos elétricos simples)",
											"magnetismo (ímãs e campo magnético)",
											"ondas (classificações)"],
					  "Ciências Humanas":["Lugar, paisagem e espaço geográfico",
										   "noções básicas de cartografia e geomorfologia",
										   "paisagens naturais e suas relações biogeográficas (os grandes biomas terrestres)",
										   "aspectos naturais e socioeconômicos do Brasil",
										   "questões ambientais gerais e as relações sociedade-natureza",
										   "aspectos gerais do crescimento, distribuição e movimentos migratórios populacionais",
										   "organização geopolítica do mundo contemporâneo e os conflitos armados regionais",
										   "o cenário econômico mundial no contexto da globalização",
										   "noções gerais dos aspectos geopolíticos no mundo contemporâneo",
										   "a Antiguidade Clássica (Grécia e Roma)",
										   "a Alta Idade Média (os Impérios Cristãos e o Islamismo); a Formação do Feudalismo",
										   "a transição",
										   "feudo-capitalista",
										   "Estados Modernos Absolutistas",
										   "a expansão marítima",
										   "a colonização da América",
										   "o Iluminismo e as Revoluções Burguesas",
										   "a crise do sistema colonial e a América independente",
										   "o Brasil Imperial",
										   "o século XIX: Liberalismo, Nacionalismo, Socialismo e Imperialismo",
										   "o Brasil Republicano: a República Velha, a Era Vargas, o Período Democrático",
										   "a Primeira e a Segunda Guerras Mundiais",
										   "a Guerra Fria",
										   "a Ditadura Militar no Brasil",
										   "a crise do Socialismo Real",
										   "o Neoliberalismo",
										   "Liberalismo econômico"]]
		let numberOfQuestionPerTopic = ["Matemática": 15,
										"Português": 15,
										"Ciências Naturais": 15,
										"Ciências Humanas": 5]
		let essay = ["Tema":"considera-se se o texto do candidato atende ao tema proposto. A fuga completa ao tema proposto é motivo suficiente para que a redação não seja corrigida em qualquer outro de seus aspectos, recebendo nota 0 (zero) total.",
					 "Estrutura":"consideram-se aqui, conjuntamente, os aspectos referentes ao gênero/tipo de texto proposto e à coerência das ideias. A fuga completa ao gênero/tipo de texto é motivo suficiente para que a redação não seja corrigida em qualquer outro de seus aspectos, recebendo nota 0 (zero) total. Avalia-se aqui como o candidato sustenta seu ponto de vista em termos argumentativos e como essa argumentação está organizada, considerando-se a macroestrutura do texto (introdução, desenvolvimento e conclusão). Será considerada aspecto negativo a referência direta à situação imediata de produção textual (ex.: como afirma o autor do primeiro texto/da coletânea/do texto I; como solicitado nesta prova/proposta de redação). Na coerência, será observada, além da pertinência dos argumentos mobilizados para a defesa do ponto de vista, a capacidade do candidato de encadear as ideias de forma lógica e coerente (progressão textual). Serão consideradas aspectos negativos a presença de contradições entre as ideias, a falta de partes da macroestrutura do texto, a falta de desenvolvimento das ideias e a presença de conclusões não decorrentes do que foi previamente exposto.",
					 "Expressão":"consideram-se nesse item os aspectos referentes à coesão textual e ao domínio da norma-padrão da língua portuguesa. Na coesão, avalia-se a utilização dos recursos coesivos da língua (anáforas, catáforas, substituições, conjunções etc.), de modo a tornar a relação entre frases e períodos e entre os parágrafos do texto mais clara e precisa. Serão considerados aspectos negativos as quebras entre frases ou parágrafos e o emprego inadequado de recursos coesivos. Na modalidade, serão examinados os aspectos gramaticais, tais como ortografia, acentuação, pontuação, regência, concordância (verbal e nominal) etc., bem como a escolha lexical (precisão vocabular) e o grau de formalidade/informalidade expressa em palavras e expressões."]

		let notice = Notice(topics: topics,
							numberOfQuestionsPerTopic: numberOfQuestionPerTopic,
							essay: essay,
							linkNotice: "https://cti.feb.unesp.br/Home/vestibulinho/vestibulinho-2021.pdf",
							durationTime: "4:30")

		let dummySchool: [School] = [School(name: "Colégio Técnico Industrial",
											location: ["Bauru, Guaratinguetá, Jaboticabal"],
											logo: UIImage(named: "logoCTI")!,
											notice: notice,
											tests: [dummyTest[0]]),
									 School(name: "COTUCA",
											location: ["Campinas"],
											logo: UIImage(named: "logoCOTUCA")!,
											notice: notice,
											tests: [dummyTest[1], dummyTest[2]]),
									 School(name: "ETEC",
											location: ["Estado de São Paulo"],
											logo: UIImage(named: "logoETEC")!,
											notice: notice,
											tests: [dummyTest[3], dummyTest[4]])]

		return dummySchool
	}
}
